name: Run the wokrflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get code

        uses: actions/checkout@v6

      - name: install node

        uses: actions/setup-node@v5

        with:
          node-version: 18

      - name: install depedencies

        run: npm install

      - name: build

        run: npm run build

      - name: print evemt name

        run: echo ${{github.event_name}}
